-- Kameraz.com — Supabase SQL
--
-- SQL Editor-də SIRAYLA:
--   1) supabase/full-setup.sql   — cədvəllər + seed
--   2) supabase/03-storage.sql   — şəkil yükləmə (Cloudinary lazım deyil)
--
-- Authentication → Users → admin@kameraz.com yarat (Auto Confirm)
